from styles import css
import streamlit as st

st.set_page_config(page_title="Conclusion", layout="wide", page_icon="📝")
css()

st.header("📝 Conclusion & Recommendations")

st.success("### Key Takeaways")
st.markdown("""
Our analysis of the Superstore Sales dataset successfully identified distinct patterns in both customer behavior and product purchasing affinities. By implementing a multi-page Streamlit application, we were able to interactively explore these patterns using two distinct machine learning techniques: DBSCAN for customer segmentation and the Apriori algorithm for market basket analysis. The study highlights that while the majority of our customers follow a standard purchasing cadence, there are significant outliers and hidden product relationships that can be leveraged to optimize sales strategies.
""")

col1, col2 = st.columns(2)
with col1:
    st.subheader("Cluster Insights (DBSCAN)")
    st.markdown("""
    The DBSCAN clustering analysis revealed two primary groups of interest. The largest cluster represents our "Core Customers," who exhibit steady, predictable buying habits with average frequency and monetary value. More importantly, the algorithm identified a significant number of "Noise" points (Cluster -1). Far from being irrelevant, these outliers often represented our highest-value customers—those placing infrequent but massive bulk orders. These "whale" customers do not fit the standard retail pattern and likely represent B2B clients who require a different engagement strategy than the standard consumer base.""")
    
with col2:
    st.subheader("Product Associations (Apriori)")
    st.markdown("""
   The Apriori algorithm uncovered strong associative rules with high "lift" values, particularly within the Office Supplies category. We observed a strong correlation between purchases of Binders and Paper, suggesting these items are frequently consumed together. Additionally, a valuable cross-category pattern emerged where customers purchasing Furniture often triggered subsequent or concurrent purchases in the Storage sub-category. These findings indicate that customers outfitting an office have a predictable need for organization solutions, which is currently an under-utilized cross-selling opportunity.
    """)

st.info("### Final Recommendation")
st.write("""
         Based on these insights, we recommend two immediate actions. First, the "Related Products" section on the e-commerce checkout page should be automated using the specific rules generated by our Apriori analysis (e.g., prompting Storage add-ons when Furniture is in the cart) to increase average order value. Second, the marketing team should segment the "Noise" customers identified by DBSCAN into a specialized "High-Volume Account" list. These clients should be targeted with personalized account management or bulk-discount incentives rather than standard mass-marketing campaigns, as their purchasing behavior suggests they are business entities rather than individual shoppers.
         """)